/**
 * PAW Path Constants
 *
 * @fileoverview Central module for all PAW path resolution. Every path used
 * by the PAW runtime, gates, hooks, or bootstrapper is derived from here.
 *
 * Layout:
 *   .github/PAW/      — Framework core (runtime, types, commands)
 *   .paw/             — Project-specific installed content (gates, hooks, db, logs)
 *
 * @module .github/PAW/paw-paths
 * @author PAW
 * @version 1.0.0
 * @since 3.0.0
 */

import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

/**
 * Absolute path to the PAW core directory (.github/PAW/).
 */
export const PAW_CORE_DIR = __dirname;

/**
 * Absolute path to the project root (two levels above .github/PAW/).
 */
export const PROJECT_ROOT = path.resolve(__dirname, '../..');

/**
 * Absolute path to the installed PAW directory (.paw/).
 */
export const PAW_DIR = path.join(PROJECT_ROOT, '.paw');

/**
 * Absolute path to the project-specific gates directory (.paw/gates/).
 */
export const GATES_DIR = path.join(PAW_DIR, 'gates');

/**
 * Absolute path to the project-specific hooks directory (.paw/hooks/).
 */
export const HOOKS_DIR = path.join(PAW_DIR, 'hooks');

/**
 * Absolute path to the project-specific plugins directory (.paw/plugins/).
 */
export const PLUGINS_DIR = path.join(PAW_DIR, 'plugins');

/**
 * Absolute path to the PAW SQLite database (.paw/paw.sqlite).
 */
export const DB_PATH = path.join(PAW_DIR, 'paw.sqlite');

/**
 * Absolute path to the PAW hook activity log (.paw/paw.log).
 */
export const LOG_PATH = path.join(PAW_DIR, 'paw.log');

/**
 * Absolute path to the .pawignore file at project root.
 */
export const PAWIGNORE_PATH = path.join(PROJECT_ROOT, '.pawignore');

/**
 * Absolute path to the hooks.json configuration file (.github/hooks/hooks.json).
 * This is the standard Copilot location — Copilot reads hooks.json from here.
 */
export const HOOKS_JSON_PATH = path.join(
  PROJECT_ROOT,
  '.github',
  'hooks',
  'hooks.json',
);

/**
 * Absolute path to the SDK session config output (.paw/sdk-session.ts).
 * Generated by the SDKAdapter when surface is "sdk" or "all".
 */
export const SDK_SESSION_PATH = path.join(PAW_DIR, 'sdk-session.ts');

/**
 * Absolute path to the PAW surface config (.paw/config.json).
 * Controls which surface adapter(s) pawSync.ts generates configs for.
 */
export const PAW_CONFIG_PATH = path.join(PAW_DIR, 'config.json');

/**
 * Read an optional path from .paw/config.json relative to project root.
 * Returns the resolved absolute path, or null when the key is absent.
 *
 * @param key - JSON key in config (e.g. `"tasksDir"`)
 * @returns Absolute path or null
 */
export function getConfigPath(key: string): string | null {
  if (!existsSync(PAW_CONFIG_PATH)) return null;
  try {
    const raw = readFileSync(PAW_CONFIG_PATH, 'utf-8');
    const config = JSON.parse(raw);
    if (typeof config[key] === 'string') {
      return path.join(PROJECT_ROOT, config[key]);
    }
  } catch {
    /* parse failure — return null */
  }
  return null;
}

/**
 * Resolve the tasks directory from `.paw/config.json` `tasksDir` key.
 * Returns null when the project has not configured a tasks directory.
 *
 * @returns Absolute path to the tasks directory, or null
 */
export function getTasksDir(): string | null {
  return getConfigPath('tasksDir');
}

/**
 * Absolute path to the installed PAW tsconfig (.paw/tsconfig.json).
 * Outputted by paw init from the template in .github/PAW/templates/.
 */
export const PAW_TSCONFIG = path.join(PAW_DIR, 'tsconfig.json');

/**
 * Relative (from project root) path to the installed PAW tsconfig — for CLI commands.
 */
export const PAW_TSCONFIG_REL = '.paw/tsconfig.json';

/**
 * Absolute path to the tsconfig template shipped with PAW core.
 */
export const PAW_TSCONFIG_TEMPLATE = path.join(
  PAW_CORE_DIR,
  'templates',
  'tsconfig.json',
);

/**
 * Relative (from project root) path to pawGates.ts — for CLI commands.
 */
export const PAW_GATES_REL = '.github/PAW/pawGates.ts';

/**
 * Cached .pawignore patterns. Loaded lazily on first call to isPathIgnored().
 */
let _ignorePatterns: RegExp[] | null = null;

/**
 * Load and cache .pawignore exclude patterns.
 * Falls back to a minimal default set if the file doesn't exist.
 *
 * @returns Array of compiled RegExp patterns
 */
function loadIgnorePatterns(): RegExp[] {
  if (_ignorePatterns) return _ignorePatterns;

  const defaultExcludes = ['node_modules', '.next', '.git', 'coverage', 'dist'];
  const lines = existsSync(PAWIGNORE_PATH)
    ? readFileSync(PAWIGNORE_PATH, 'utf-8').split('\n')
    : defaultExcludes;

  _ignorePatterns = lines
    .map((l) => l.trim())
    .filter((l) => l.length > 0 && !l.startsWith('#'))
    .map((pattern) => {
      const escaped = pattern
        .replace(/[.+^${}()|[\]\\]/g, '\\$&')
        .replace(/\*\*/g, '.*')
        .replace(/\*/g, '[^/]*')
        .replace(/\?/g, '[^/]');
      return new RegExp(escaped);
    });

  return _ignorePatterns;
}

/**
 * Check whether a relative file path is excluded by .pawignore or PAW's
 * built-in exclusions (.github/PAW/ and .paw/).
 *
 * @param {string} relativePath - Forward-slash path relative to project root
 * @returns True if the path should be skipped by PAW hooks and gates
 */
export function isPathIgnored(relativePath: string): boolean {
  if (
    relativePath.startsWith('.github/PAW/') ||
    relativePath.startsWith('.paw/')
  ) {
    return true;
  }
  return loadIgnorePatterns().some((pattern) => pattern.test(relativePath));
}

/**
 * Convert any file path (absolute or relative) to a project-relative,
 * forward-slash form suitable for cross-platform comparison.
 * Strips the project root prefix (case-insensitive match) and drive letters
 * while preserving the original casing of the path segments.
 *
 * @param {string} filePath - Absolute or relative file path
 * @returns Project-relative normalized path (e.g. "src/lib/foo.ts")
 */
export function toProjectRelative(filePath: string): string {
  const forwardSlash = filePath.replace(/\\/g, '/');
  const rootForward = PROJECT_ROOT.replace(/\\/g, '/');
  const lower = forwardSlash.toLowerCase();
  const rootLower = rootForward.toLowerCase();
  if (lower.startsWith(rootLower + '/')) {
    return forwardSlash.slice(rootForward.length + 1);
  }
  if (lower.startsWith(rootLower)) {
    return forwardSlash.slice(rootForward.length);
  }
  return forwardSlash.replace(/^[a-z]:\//i, '').replace(/^\//, '');
}
