/**
 * PAW Git Hook Configurator
 *
 * @fileoverview Writes thin Git hook shims into .git/hooks/ that invoke
 * pawGates.ts. Replaces Husky + lint-staged with a single system where
 * humans and agents run the same quality gates.
 *
 * Commands:
 *   install    Write all managed hooks (pre-commit, commit-msg, pre-push, post-checkout, post-merge)
 *   uninstall  Remove PAW-managed hooks (leaves non-PAW hooks untouched)
 *   status     Show which hooks are installed
 *
 * @module .github/PAW/pawHooks
 * @author Typeir
 * @version 2.0.0
 * @since 3.0.0
 */

import { execSync } from 'node:child_process';
import {
    chmodSync,
    existsSync,
    mkdirSync,
    readFileSync,
    unlinkSync,
    writeFileSync,
} from 'node:fs';
import path from 'node:path';
import * as logger from './paw-logger';
import { PAW_CONFIG_PATH, PAW_GATES_REL, PAW_TSCONFIG_REL } from './paw-paths';

const PAW_MARKER = '# generated by PAW — do not edit';

/**
 * Configuration for a single Git hook.
 *
 * @interface HookConfig
 * @property {string} name - Git hook name (e.g. 'pre-commit')
 * @property {string} [flags] - CLI flags passed to pawGates.ts (omit to skip gates entirely)
 * @property {string} description - Description shown during install and in the hook header
 * @property {string} [command] - Full override command (replaces the default pawGates invocation)
 * @property {string[]} [appendCommands] - Additional commands appended after the main command
 */
interface HookConfig {
  name: string;
  flags?: string;
  description: string;
  command?: string;
  appendCommands?: string[];
}

/**
 * Load hook configurations from .paw/config.json.
 * Falls back to a minimal default (pre-commit gates only) if no config exists.
 *
 * @returns {HookConfig[]} Array of hook configurations
 */
function loadHookConfigs(): HookConfig[] {
  if (!existsSync(PAW_CONFIG_PATH)) {
    logger.warn(
      'No .paw/config.json found — using default pre-commit gate only',
    );
    return [
      {
        name: 'pre-commit',
        flags: '--changed-only --staged',
        description: 'Run quality gates on staged files before commit',
      },
    ];
  }

  const config = JSON.parse(readFileSync(PAW_CONFIG_PATH, 'utf-8'));
  const hooks: HookConfig[] | undefined = config.gitHooks;

  if (!hooks || !Array.isArray(hooks) || hooks.length === 0) {
    logger.warn(
      'No gitHooks defined in .paw/config.json — using default pre-commit gate only',
    );
    return [
      {
        name: 'pre-commit',
        flags: '--changed-only --staged',
        description: 'Run quality gates on staged files before commit',
      },
    ];
  }

  return hooks;
}

const HOOK_CONFIGS: HookConfig[] = loadHookConfigs();

/**
 * Locate the .git/hooks directory using git rev-parse.
 *
 * @returns Absolute path to the hooks directory
 */
function getGitHooksDir(): string {
  try {
    const gitDir = execSync('git rev-parse --git-dir', {
      encoding: 'utf-8',
      timeout: 5000,
      stdio: ['pipe', 'pipe', 'pipe'],
    }).trim();
    return path.resolve(gitDir, 'hooks');
  } catch {
    throw new Error('Not a git repository — cannot install hooks');
  }
}

/**
 * Generate the shell shim content for a hook.
 * Uses bash with a shebang that works on all platforms (Git for Windows ships bash).
 *
 * @param config - Hook configuration
 * @returns Shell script content
 */
function generateHookScript(config: HookConfig): string {
  const lines: string[] = [
    '#!/usr/bin/env bash',
    PAW_MARKER,
    `# ${config.description}`,
    '',
  ];

  if (config.command) {
    lines.push(config.command);
  } else if (config.flags) {
    lines.push(
      `npx tsx --tsconfig ${PAW_TSCONFIG_REL} ${PAW_GATES_REL} ${config.flags}`,
    );
  }

  if (config.appendCommands) {
    lines.push('');
    for (const cmd of config.appendCommands) {
      lines.push(cmd);
    }
  }

  lines.push('');
  return lines.join('\n');
}

/**
 * Check whether a hook file was generated by PAW.
 *
 * @param hookPath - Absolute path to the hook file
 * @returns True if the file contains the PAW marker
 */
function isPawHook(hookPath: string): boolean {
  if (!existsSync(hookPath)) return false;
  const content = readFileSync(hookPath, 'utf-8');
  return content.includes(PAW_MARKER);
}

/**
 * Install Git hooks by writing shim scripts into .git/hooks/.
 * Skips non-PAW hooks to avoid overwriting custom hooks.
 */
function install(): void {
  const hooksDir = getGitHooksDir();
  mkdirSync(hooksDir, { recursive: true });

  let installed = 0;
  let skipped = 0;

  for (const config of HOOK_CONFIGS) {
    const hookPath = path.join(hooksDir, config.name);

    if (existsSync(hookPath) && !isPawHook(hookPath)) {
      logger.warn(
        `Skipping ${config.name} — existing non-PAW hook found. Remove it manually to let PAW manage it.`,
      );
      skipped++;
      continue;
    }

    writeFileSync(hookPath, generateHookScript(config), { mode: 0o755 });
    try {
      chmodSync(hookPath, 0o755);
    } catch {
      /** Windows — chmod not needed, Git for Windows handles execute bit */
    }

    logger.success(`Installed ${config.name} hook`);
    installed++;
  }

  logger.pawOutro(
    `${installed} hook(s) installed${skipped > 0 ? `, ${skipped} skipped` : ''}`,
  );
}

/**
 * Remove PAW-managed hooks from .git/hooks/.
 * Only removes hooks that contain the PAW marker.
 */
function uninstall(): void {
  const hooksDir = getGitHooksDir();
  let removed = 0;

  for (const config of HOOK_CONFIGS) {
    const hookPath = path.join(hooksDir, config.name);

    if (isPawHook(hookPath)) {
      unlinkSync(hookPath);
      logger.success(`Removed ${config.name} hook`);
      removed++;
    }
  }

  if (removed === 0) {
    logger.info('No PAW hooks found to remove.');
  } else {
    logger.pawOutro(`${removed} hook(s) removed`);
  }
}

/**
 * Show the current status of Git hooks.
 */
function status(): void {
  const hooksDir = getGitHooksDir();

  for (const config of HOOK_CONFIGS) {
    const hookPath = path.join(hooksDir, config.name);

    if (!existsSync(hookPath)) {
      logger.info(`${config.name} — not installed`);
    } else if (isPawHook(hookPath)) {
      logger.success(`${config.name} — PAW managed`);
    } else {
      logger.warn(`${config.name} — non-PAW (custom hook)`);
    }
  }
}

/**
 * CLI entry point. Parses argv for install, uninstall, or status commands.
 */
const command = process.argv[2];

switch (command) {
  case 'install':
    logger.pawIntro('PAW Git Hook Configurator');
    install();
    break;
  case 'uninstall':
    logger.pawIntro('PAW Git Hook Configurator');
    uninstall();
    break;
  case 'status':
    logger.pawIntro('PAW Git Hook Status');
    status();
    break;
  default:
    logger.pawIntro('PAW Git Hook Configurator');
    logger.info(
      'Usage: npx tsx --tsconfig tsconfig.scripts.json .github/PAW/pawHooks.ts <command>',
    );
    logger.message('Commands:');
    logger.message('  install    Write all managed hooks into .git/hooks/');
    logger.message('  uninstall  Remove PAW-managed hooks');
    logger.message('  status     Show hook status');
    break;
}
