/**
 * PAW SDK Surface Adapter
 *
 * @fileoverview Generates a TypeScript session configuration file for the
 * Copilot SDK (`@github/copilot-sdk`). Instead of JSON hook configs, the
 * SDK uses programmatic callbacks in a `createSession()` call. This adapter
 * produces a `.ts` file that imports PAW hook handlers and wires them into
 * the SDK's typed callback system.
 *
 * @module .github/PAW/adapters/sdk.adapter
 * @author Typeir
 * @version 1.0.0
 * @since 4.0.0
 */

import { SDK_EVENT_MAP, resolveEventName } from './eventMap';
import type { PawHookDef, PawSurfaceAdapter, SurfaceHookOutput } from './types';
import { PawEvent } from './types';

/**
 * SDK callback group: maps SDK callback names to their hook handler file paths.
 *
 * @typedef {Record<string, string[]>} SDKCallbackGroup
 */
type SDKCallbackGroup = Record<string, string[]>;

/**
 * Adapter that generates a TypeScript session configuration file for the
 * Copilot SDK. The output is a `.ts` file with a `createPawSession()` function
 * that wires PAW hook handlers into SDK callbacks.
 *
 * @implements {PawSurfaceAdapter}
 */
export class SDKAdapter implements PawSurfaceAdapter {
  /** @inheritdoc */
  readonly name = 'sdk' as const;

  /**
   * Relative path to the hooks directory from project root.
   */
  private readonly hookBase: string;

  /**
   * @param hookBase - Relative path to .paw/hooks/ directory
   */
  constructor(hookBase: string = '.paw/hooks') {
    this.hookBase = hookBase;
  }

  /** @inheritdoc */
  generateHookConfig(hooks: PawHookDef[]): SurfaceHookOutput {
    const callbackGroups: SDKCallbackGroup = {};

    for (const hook of hooks) {
      const callbackName = this.getEventName(hook.event);
      if (!callbackName) continue;

      if (!callbackGroups[callbackName]) {
        callbackGroups[callbackName] = [];
      }
      callbackGroups[callbackName].push(`${this.hookBase}/${hook.file}`);
    }

    const content = this.generateTypeScript(callbackGroups);

    return {
      filePath: '.paw/sdk-session.ts',
      content,
    };
  }

  /** @inheritdoc */
  getEventName(event: PawEvent): string | null {
    return resolveEventName(event, SDK_EVENT_MAP);
  }

  /**
   * SDK adapter does not use shell commands — hooks are direct TypeScript
   * imports. Returns a descriptor object for documentation purposes.
   *
   * @inheritdoc
   */
  getCommandFormat(script: string, timeout: number): Record<string, unknown> {
    return {
      type: 'sdk-callback',
      handler: script,
      timeoutMs: timeout * 1000,
    };
  }

  /**
   * Generate the TypeScript session configuration file content.
   *
   * @param callbackGroups - SDK callback names mapped to handler file paths
   * @returns TypeScript source code as a string
   */
  private generateTypeScript(callbackGroups: SDKCallbackGroup): string {
    const lines: string[] = [
      '/**',
      ' * PAW SDK Session Configuration (Auto-Generated)',
      ' *',
      ' * @fileoverview Generated by pawSync.ts via SDKAdapter.',
      ' * Do not edit manually — re-run `npx tsx .github/PAW/pawSync.ts` to regenerate.',
      ' *',
      ' * @module .paw/sdk-session',
      ' * @version 1.0.0',
      ' */',
      '',
      '/**',
      ' * Hook handler file paths grouped by SDK callback name.',
      ' * Each callback invokes its handlers sequentially.',
      ' */',
      `export const PAW_SDK_HOOKS: Record<string, string[]> = ${JSON.stringify(callbackGroups, null, 2)};`,
      '',
      '/**',
      ' * Create a Copilot SDK session config with PAW hooks wired in.',
      ' * Import this in your SDK integration to get PAW enforcement.',
      ' *',
      ' * @example',
      ' * ```typescript',
      " * import { createPawSessionConfig } from './.paw/sdk-session';",
      " * import { CopilotClient } from '@github/copilot-sdk';",
      ' *',
      ' * const client = new CopilotClient();',
      ' * const session = await client.createSession(createPawSessionConfig());',
      ' * ```',
      ' *',
      ' * @returns Partial session config with hooks callbacks',
      ' */',
      'export function createPawSessionConfig(): Record<string, unknown> {',
      '  return {',
      '    hooks: PAW_SDK_HOOKS,',
      '    skillDirectories: [".github/skills"],',
      '  };',
      '}',
      '',
    ];

    return lines.join('\n');
  }
}
